/* eslint-disable */
// AUTO-GENERATED by scripts/import-warp-themes.js
// Source: https://github.com/warpdotdev/themes (standard/)
// Do not edit by hand. Re-run: pnpm run import-themes

import type { AppTheme } from './types';

export const warpImportedThemes: AppTheme[] = [
  {
    "name": "gruvbox-dark",
    "label": "Gruvbox Dark",
    "variant": "darker",
    "ui": {
      "bg": "#282828",
      "bgLight": "#353535",
      "bgLighter": "#4e4e4e",
      "menuBg": "#3c3c3c",
      "menuBorder": "#757575",
      "menuHover": "#424242",
      "fg": "#ebdbb2",
      "fgMuted": "#d6b561",
      "accent": "#458588",
      "border": "#686868",
      "hover": "#474747"
    },
    "terminal": {
      "background": "#282828",
      "foreground": "#ebdbb2",
      "cursor": "#458588",
      "cursorAccent": "#282828",
      "selectionBackground": "#4e4e4e",
      "black": "#282828",
      "red": "#cc241d",
      "green": "#98971a",
      "yellow": "#d79921",
      "blue": "#458588",
      "magenta": "#b16286",
      "cyan": "#689d6a",
      "white": "#a89984",
      "brightBlack": "#928374",
      "brightRed": "#fb4934",
      "brightGreen": "#b8bb26",
      "brightYellow": "#fabd2f",
      "brightBlue": "#83a598",
      "brightMagenta": "#d3869b",
      "brightCyan": "#8ec07c",
      "brightWhite": "#ebdbb2"
    },
    "rgb": {
      "uiBg": "40, 40, 40",
      "terminalBg": "40, 40, 40"
    }
  },
  {
    "name": "gruvbox-light",
    "label": "Gruvbox Light",
    "variant": "lighter",
    "ui": {
      "bg": "#fbf1c7",
      "bgLight": "#f9ebaf",
      "bgLighter": "#f6df80",
      "menuBg": "#f8e7a1",
      "menuBorder": "#f1cd38",
      "menuHover": "#f8e597",
      "fg": "#3c3836",
      "fgMuted": "#726a66",
      "accent": "#458588",
      "border": "#f3d350",
      "hover": "#f7e38e"
    },
    "terminal": {
      "background": "#fbf1c7",
      "foreground": "#3c3836",
      "cursor": "#458588",
      "cursorAccent": "#fbf1c7",
      "selectionBackground": "#f6df80",
      "black": "#fbf1c7",
      "red": "#cc241d",
      "green": "#98971a",
      "yellow": "#d79921",
      "blue": "#458588",
      "magenta": "#b16286",
      "cyan": "#689d6a",
      "white": "#7c6f64",
      "brightBlack": "#928374",
      "brightRed": "#9d0006",
      "brightGreen": "#79740e",
      "brightYellow": "#b57614",
      "brightBlue": "#076678",
      "brightMagenta": "#8f3f71",
      "brightCyan": "#427b58",
      "brightWhite": "#3c3836"
    },
    "rgb": {
      "uiBg": "251, 241, 199",
      "terminalBg": "251, 241, 199"
    }
  },
  {
    "name": "solarized-dark",
    "label": "Solarized Dark",
    "variant": "darker",
    "ui": {
      "bg": "#002b36",
      "bgLight": "#003f50",
      "bgLighter": "#006883",
      "menuBg": "#004b5f",
      "menuBorder": "#00a5cf",
      "menuHover": "#005469",
      "fg": "#839496",
      "fgMuted": "#525f61",
      "accent": "#268bd2",
      "border": "#0091b6",
      "hover": "#005c73"
    },
    "terminal": {
      "background": "#002b36",
      "foreground": "#839496",
      "cursor": "#268bd2",
      "cursorAccent": "#002b36",
      "selectionBackground": "#006883",
      "black": "#073642",
      "red": "#dc322f",
      "green": "#859900",
      "yellow": "#b58900",
      "blue": "#268bd2",
      "magenta": "#d33682",
      "cyan": "#2aa198",
      "white": "#eee8d5",
      "brightBlack": "#002b36",
      "brightRed": "#cb4b16",
      "brightGreen": "#586e75",
      "brightYellow": "#657b83",
      "brightBlue": "#839496",
      "brightMagenta": "#6c71c4",
      "brightCyan": "#93a1a1",
      "brightWhite": "#fdf6e3"
    },
    "rgb": {
      "uiBg": "0, 43, 54",
      "terminalBg": "0, 43, 54"
    }
  },
  {
    "name": "solarized-light",
    "label": "Solarized Light",
    "variant": "lighter",
    "ui": {
      "bg": "#fdf6e3",
      "bgLight": "#fbeecb",
      "bgLighter": "#f8df9c",
      "menuBg": "#faeabd",
      "menuBorder": "#f3c854",
      "menuHover": "#fae7b3",
      "fg": "#586e75",
      "fgMuted": "#8ba1a8",
      "accent": "#268bd2",
      "border": "#f5d06c",
      "hover": "#f9e4aa"
    },
    "terminal": {
      "background": "#fdf6e3",
      "foreground": "#586e75",
      "cursor": "#268bd2",
      "cursorAccent": "#fdf6e3",
      "selectionBackground": "#f8df9c",
      "black": "#073642",
      "red": "#dc322f",
      "green": "#859900",
      "yellow": "#b58900",
      "blue": "#268bd2",
      "magenta": "#d33682",
      "cyan": "#2aa198",
      "white": "#eee8d5",
      "brightBlack": "#002b36",
      "brightRed": "#cb4b16",
      "brightGreen": "#586e75",
      "brightYellow": "#657b83",
      "brightBlue": "#839496",
      "brightMagenta": "#6c71c4",
      "brightCyan": "#93a1a1",
      "brightWhite": "#fdf6e3"
    },
    "rgb": {
      "uiBg": "253, 246, 227",
      "terminalBg": "253, 246, 227"
    }
  },
  {
    "name": "one-dark",
    "label": "One Dark",
    "variant": "darker",
    "ui": {
      "bg": "#1e2127",
      "bgLight": "#292d35",
      "bgLighter": "#3f4652",
      "menuBg": "#30353e",
      "menuBorder": "#616a7d",
      "menuHover": "#343944",
      "fg": "#abb2bf",
      "fgMuted": "#717d93",
      "accent": "#61afef",
      "border": "#555e6f",
      "hover": "#393e4a"
    },
    "terminal": {
      "background": "#1e2127",
      "foreground": "#abb2bf",
      "cursor": "#61afef",
      "cursorAccent": "#1e2127",
      "selectionBackground": "#3f4652",
      "black": "#1e2127",
      "red": "#e06c75",
      "green": "#98c379",
      "yellow": "#d19a66",
      "blue": "#61afef",
      "magenta": "#c678dd",
      "cyan": "#56b6c2",
      "white": "#abb2bf",
      "brightBlack": "#5c6370",
      "brightRed": "#e06c75",
      "brightGreen": "#98c379",
      "brightYellow": "#d19a66",
      "brightBlue": "#61afef",
      "brightMagenta": "#c678dd",
      "brightCyan": "#56b6c2",
      "brightWhite": "#ffffff"
    },
    "rgb": {
      "uiBg": "30, 33, 39",
      "terminalBg": "30, 33, 39"
    }
  },
  {
    "name": "monokai",
    "label": "Monokai Pro",
    "variant": "darker",
    "ui": {
      "bg": "#2d2a2e",
      "bgLight": "#3a363b",
      "bgLighter": "#544f56",
      "menuBg": "#423d43",
      "menuBorder": "#7b737e",
      "menuHover": "#474249",
      "fg": "#fcfcfa",
      "fgMuted": "#d6d6ba",
      "accent": "#c1c0c0",
      "border": "#6e6771",
      "hover": "#4c474e"
    },
    "terminal": {
      "background": "#2d2a2e",
      "foreground": "#fcfcfa",
      "cursor": "#c1c0c0",
      "cursorAccent": "#2d2a2e",
      "selectionBackground": "#544f56",
      "black": "#2d2a2e",
      "red": "#ff6188",
      "green": "#a9dc76",
      "yellow": "#ffd866",
      "blue": "#6ab0f3",
      "magenta": "#ab9df2",
      "cyan": "#78dce8",
      "white": "#fcfcfa",
      "brightBlack": "#727072",
      "brightRed": "#ff6188",
      "brightGreen": "#a9dc76",
      "brightYellow": "#ffd866",
      "brightBlue": "#6ab0f3",
      "brightMagenta": "#ab9df2",
      "brightCyan": "#78dce8",
      "brightWhite": "#fcfcfa"
    },
    "rgb": {
      "uiBg": "45, 42, 46",
      "terminalBg": "45, 42, 46"
    }
  },
  {
    "name": "ayu-dark",
    "label": "Ayu Dark",
    "variant": "darker",
    "ui": {
      "bg": "#0a0e14",
      "bgLight": "#131a25",
      "bgLighter": "#243247",
      "menuBg": "#18212f",
      "menuBorder": "#3d557a",
      "menuHover": "#1b2636",
      "fg": "#b3b1ad",
      "fgMuted": "#827f78",
      "accent": "#53bdfa",
      "border": "#354a69",
      "hover": "#1e2b3d"
    },
    "terminal": {
      "background": "#0a0e14",
      "foreground": "#b3b1ad",
      "cursor": "#53bdfa",
      "cursorAccent": "#0a0e14",
      "selectionBackground": "#243247",
      "black": "#01060e",
      "red": "#ea6c73",
      "green": "#91b362",
      "yellow": "#f9af4f",
      "blue": "#53bdfa",
      "magenta": "#fae994",
      "cyan": "#90e1c6",
      "white": "#c7c7c7",
      "brightBlack": "#686868",
      "brightRed": "#f07178",
      "brightGreen": "#c2d94c",
      "brightYellow": "#ffb454",
      "brightBlue": "#59c2ff",
      "brightMagenta": "#ffee99",
      "brightCyan": "#95e6cb",
      "brightWhite": "#ffffff"
    },
    "rgb": {
      "uiBg": "10, 14, 20",
      "terminalBg": "10, 14, 20"
    }
  },
  {
    "name": "ayu-light",
    "label": "Ayu Light",
    "variant": "lighter",
    "ui": {
      "bg": "#f8f9fa",
      "bgLight": "#e9ecef",
      "bgLighter": "#cbd3da",
      "menuBg": "#e0e5e9",
      "menuBorder": "#9fadba",
      "menuHover": "#dae0e5",
      "fg": "#5c6166",
      "fgMuted": "#8e949a",
      "accent": "#ffaa33",
      "border": "#aeb9c5",
      "hover": "#d4dae1"
    },
    "terminal": {
      "background": "#f8f9fa",
      "foreground": "#5c6166",
      "cursor": "#ffaa33",
      "cursorAccent": "#f8f9fa",
      "selectionBackground": "#cbd3da",
      "black": "#000000",
      "red": "#ea6c6d",
      "green": "#6cbf43",
      "yellow": "#eca944",
      "blue": "#3199e1",
      "magenta": "#9e75c7",
      "cyan": "#46ba94",
      "white": "#c7c7c7",
      "brightBlack": "#686868",
      "brightRed": "#f07171",
      "brightGreen": "#86b300",
      "brightYellow": "#f2ae49",
      "brightBlue": "#399ee6",
      "brightMagenta": "#a37acc",
      "brightCyan": "#4cbf99",
      "brightWhite": "#d1d1d1"
    },
    "rgb": {
      "uiBg": "248, 249, 250",
      "terminalBg": "248, 249, 250"
    }
  },
  {
    "name": "github-dark",
    "label": "GitHub Dark",
    "variant": "darker",
    "ui": {
      "bg": "#0d1117",
      "bgLight": "#161d27",
      "bgLighter": "#293548",
      "menuBg": "#1c2431",
      "menuBorder": "#445979",
      "menuHover": "#1f2938",
      "fg": "#c9d1d9",
      "fgMuted": "#8d9eaf",
      "accent": "#f78166",
      "border": "#3b4d68",
      "hover": "#232e3e"
    },
    "terminal": {
      "background": "#0d1117",
      "foreground": "#c9d1d9",
      "cursor": "#f78166",
      "cursorAccent": "#0d1117",
      "selectionBackground": "#293548",
      "black": "#0d1117",
      "red": "#ff7b72",
      "green": "#3fb950",
      "yellow": "#d29922",
      "blue": "#58a6ff",
      "magenta": "#bc8cff",
      "cyan": "#76e3ea",
      "white": "#b1bac4",
      "brightBlack": "#161b22",
      "brightRed": "#ffa198",
      "brightGreen": "#56d364",
      "brightYellow": "#e3b341",
      "brightBlue": "#79c0ff",
      "brightMagenta": "#d2a8ff",
      "brightCyan": "#b3f0ff",
      "brightWhite": "#b1bac4"
    },
    "rgb": {
      "uiBg": "13, 17, 23",
      "terminalBg": "13, 17, 23"
    }
  }
];
